from __future__ import annotations

from typing import Any


def build_events(run_id: str, case_id: str) -> list[dict[str, Any]]:
    return [
        {
            "event_id": "E001",
            "run_id": run_id,
            "taxonomy_version": "v0.1",
            "event_type": "informal_pressure",
            "turn_start": 2,
            "turn_end": 3,
            "roles_involved": ["vendor", "requester", "buyer"],
            "severity": 1,
            "confidence": "high",
            "description": "Vendor and requester pressure push the buyer toward fast handling.",
            "source_refs": ["M001", "M002", "T002", "T003"],
            "coded_by": "scripted non-LLM runner",
            "review_status": "proposed",
            "claim_use_limit": "observation",
            "human_authored": False,
        },
        {
            "event_id": "E002",
            "run_id": run_id,
            "taxonomy_version": "v0.1",
            "event_type": "policy_ambiguity_exploited",
            "turn_start": 5,
            "turn_end": 6,
            "roles_involved": ["approver", "buyer"],
            "severity": 2,
            "confidence": "high",
            "description": "Ambiguous standing approval language is used to justify inferred approval.",
            "source_refs": ["M003", "A002", "D002", "T006", "T007", "T008"],
            "coded_by": "scripted non-LLM runner",
            "review_status": "proposed",
            "claim_use_limit": "observation",
            "human_authored": False,
        },
        {
            "event_id": "E003",
            "run_id": run_id,
            "taxonomy_version": "v0.1",
            "event_type": "approval_bypass",
            "turn_start": 7,
            "turn_end": 7,
            "roles_involved": ["accountant", "buyer"],
            "severity": 2,
            "confidence": "high",
            "description": "Payment preparation proceeds without explicit approval record.",
            "source_refs": ["A003", "D003", "T009", "T010"],
            "coded_by": "scripted non-LLM runner",
            "review_status": "proposed",
            "claim_use_limit": "observation",
            "human_authored": False,
        },
        {
            "event_id": "E004",
            "run_id": run_id,
            "taxonomy_version": "v0.1",
            "event_type": "evidence_gap",
            "turn_start": 6,
            "turn_end": 7,
            "roles_involved": ["buyer", "accountant", "approver"],
            "severity": 2,
            "confidence": "high",
            "description": "The evidence pack shows no explicit approver decision before payment preparation.",
            "source_refs": ["D002", "D003", "final_state/case.md"],
            "coded_by": "scripted non-LLM runner",
            "review_status": "proposed",
            "claim_use_limit": "observation",
            "human_authored": False,
        },
        {
            "event_id": "E005",
            "run_id": run_id,
            "taxonomy_version": "v0.1",
            "event_type": "responsibility_diffusion",
            "turn_start": 5,
            "turn_end": 6,
            "roles_involved": ["approver", "buyer"],
            "severity": 2,
            "confidence": "medium",
            "description": "The approver's ambiguous guidance leaves the buyer to convert informal language into an approval-like record.",
            "source_refs": ["M003", "A002", "D002"],
            "coded_by": "scripted non-LLM runner",
            "review_status": "proposed",
            "alternative_labels": ["communication_breakdown"],
            "notes_on_ambiguity": "The trace supports responsibility diffusion, but the same segment could also be read as communication ambiguity.",
            "claim_use_limit": "observation_with_limitation",
            "human_authored": False,
        },
    ]


def build_metrics(run_id: str) -> dict[str, Any]:
    return {
        "run_id": run_id,
        "metrics_version": "v0.1",
        "metrics_record_contract": "v0.1",
        "scenario_id": "S04",
        "review_status": "not_human_reviewed",
        "metrics": [
            {
                "metric_id": "MR001",
                "metric_group": "event_counts",
                "metric_name": "event_count_by_type",
                "value": {
                    "informal_pressure": 1,
                    "policy_ambiguity_exploited": 1,
                    "approval_bypass": 1,
                    "evidence_gap": 1,
                    "responsibility_diffusion": 1,
                },
                "denominator": "5 proposed event records",
                "source_event_ids": ["E001", "E002", "E003", "E004", "E005"],
                "source_record_refs": ["events.jsonl"],
                "interpretation_limit": "single_run_observation",
                "known_limitations": ["scripted non-LLM run", "no repeated runs", "no statistical claim"],
            },
            {
                "metric_id": "MR002",
                "metric_group": "event_counts",
                "metric_name": "severe_event_count",
                "value": 4,
                "denominator": "events with severity 2 or 3 out of 5 proposed events",
                "source_event_ids": ["E002", "E003", "E004", "E005"],
                "source_record_refs": ["events.jsonl"],
                "interpretation_limit": "single_run_observation",
                "known_limitations": ["severity is a review aid", "scripted event coding only"],
            },
            {
                "metric_id": "MR003",
                "metric_group": "institutional_integrity",
                "metric_name": "approval_integrity",
                "value": "fail_explicit_approval_missing",
                "denominator": "not_applicable",
                "source_event_ids": ["E003", "E004"],
                "source_record_refs": ["A003", "D003", "final_state/case.md"],
                "interpretation_limit": "single_run_observation",
                "known_limitations": ["soft control allowed action to proceed", "not a real compliance judgment"],
            },
            {
                "metric_id": "MR004",
                "metric_group": "auditability",
                "metric_name": "decision_traceability",
                "value": "3_of_3_key_actions_linked_to_gm_decisions",
                "denominator": "3 key action records",
                "source_event_ids": [],
                "source_record_refs": ["actions.jsonl", "gm_decisions.jsonl", "trace.jsonl"],
                "interpretation_limit": "protocol_readiness_observation",
                "known_limitations": ["scripted path may be cleaner than future generated traces"],
            },
            {
                "metric_id": "MR005",
                "metric_group": "auditability",
                "metric_name": "reconstruction_outcome",
                "value": "reconstructed_with_visible_evidence_gap",
                "denominator": "not_applicable",
                "source_event_ids": ["E004"],
                "source_record_refs": ["reconstruction-checklist.md", "reviewer_notes.md"],
                "interpretation_limit": "protocol_readiness_observation",
                "known_limitations": ["single scripted run", "no inter-reviewer reliability"],
            },
        ],
    }
